REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (277, 'TSHIRT', 'C', 'A', 1, 75.00, 90, 0.000, 0, 0, 0, 0.00, 0, 1504252996, 1504253791, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'bigpicture_template', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 0, NULL, '[27,28]', 'N');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (278, 'TSHIRT1', 'V', 'A', 1, 75.00, 90, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504254135, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_183_190', '{\"28\":\"190\",\"27\":\"183\"}', 'Y');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (279, 'TSHIRT2', 'V', 'A', 1, 75.00, 90, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504254020, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_183_191', '{\"28\":\"191\",\"27\":\"183\"}', 'N');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (280, 'TSHIRT3', 'V', 'A', 1, 50.00, 0, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504254057, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_184_190', '{\"28\":\"190\",\"27\":\"184\"}', 'N');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (281, 'TSHIRT4', 'V', 'A', 1, 75.00, 90, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504253883, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_184_191', '{\"28\":\"191\",\"27\":\"184\"}', 'N');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (282, 'TSHIRT5', 'V', 'A', 1, 75.00, 90, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504254102, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_185_190', '{\"28\":\"190\",\"27\":\"185\"}', 'N');
REPLACE INTO ?:products (`product_id`, `product_code`, `product_type`, `status`, `company_id`, `list_price`, `amount`, `weight`, `length`, `width`, `height`, `shipping_freight`, `low_avail_limit`, `timestamp`, `updated_timestamp`, `usergroup_ids`, `is_edp`, `edp_shipping`, `tracking`, `free_shipping`, `zero_price_action`, `is_pbp`, `is_op`, `is_oper`, `is_returnable`, `return_period`, `avail_since`, `out_of_stock_actions`, `localization`, `min_qty`, `max_qty`, `qty_step`, `list_qty_count`, `tax_ids`, `age_verification`, `age_limit`, `options_type`, `exceptions_type`, `details_layout`, `shipping_params`, `parent_product_id`, `variation_code`, `variation_options`, `is_default_variation`) VALUES (283, 'TSHIRT6', 'V', 'A', 1, 75.00, 0, 0.000, 0, 0, 0, 0.00, 0, 1504253345, 1504254252, '0', 'N', 'N', 'B', 'N', 'R', 'N', 'N', 'N', 'Y', 10, 0, 'N', '', 0, 0, 0, 0, '', 'N', 0, 'P', 'F', 'default', 'a:5:{s:16:\"min_items_in_box\";i:0;s:16:\"max_items_in_box\";i:0;s:10:\"box_length\";i:0;s:9:\"box_width\";i:0;s:10:\"box_height\";i:0;}', 277, '277_185_191', '{\"28\":\"191\",\"27\":\"185\"}', 'N');

REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (277, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (278, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (279, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (280, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (281, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (282, 224, 'M', 0);
REPLACE INTO ?:products_categories (`product_id`, `category_id`, `link_type`, `position`) VALUES (283, 224, 'M', 0);

REPLACE INTO ?:product_options (`option_id`, `product_id`, `company_id`, `option_type`, `inventory`, `regexp`, `required`, `multiupload`, `allowed_extensions`, `max_file_size`, `missing_variants_handling`, `status`, `position`, `value`) VALUES (27, 277, 1, 'S', 'Y', '', 'N', 'N', '', 0, 'M', 'A', 10, '');
REPLACE INTO ?:product_options (`option_id`, `product_id`, `company_id`, `option_type`, `inventory`, `regexp`, `required`, `multiupload`, `allowed_extensions`, `max_file_size`, `missing_variants_handling`, `status`, `position`, `value`) VALUES (28, 277, 1, 'S', 'Y', '', 'N', 'N', '', 0, 'M', 'A', 20, '');

REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (183, 27, 10, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (184, 27, 20, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (185, 27, 30, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (186, 27, 40, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (187, 27, 50, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (188, 27, 60, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (189, 28, 10, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (190, 28, 20, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (191, 28, 30, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (192, 28, 40, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');
REPLACE INTO ?:product_option_variants (`variant_id`, `option_id`, `position`, `modifier`, `modifier_type`, `weight_modifier`, `weight_modifier_type`, `point_modifier`, `point_modifier_type`, `status`) VALUES (193, 28, 50, 0.000, 'A', 0.000, 'A', 0.000, 'A', 'A');

REPLACE INTO ?:product_popularity (`product_id`, `viewed`, `added`, `deleted`, `bought`, `total`) VALUES (277, 1, 0, 0, 0, 3);

REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (277, 30.00, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (278, 30.00, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (279, 30.00, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (280, 36.00, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (281, 37.00, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (282, 23.99, 0, 10, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (282, 25.99, 0, 5, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (282, 27.99, 0, 1, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (283, 23.99, 0, 10, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (283, 25.99, 0, 5, 0);
REPLACE INTO ?:product_prices (`product_id`, `price`, `percentage_discount`, `lower_limit`, `usergroup_id`) VALUES (283, 27.99, 0, 1, 0);

REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1158, 277, 'product', 0, 1395, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1159, 278, 'product', 0, 1396, 'A', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1160, 278, 'product', 0, 1397, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1161, 279, 'product', 0, 1398, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1162, 279, 'product', 0, 1399, 'A', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1163, 279, 'product', 0, 1400, 'A', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1164, 280, 'product', 0, 1401, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1165, 280, 'product', 0, 1402, 'A', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1166, 281, 'product', 0, 1403, 'A', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1167, 281, 'product', 0, 1404, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1168, 282, 'product', 0, 1405, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1169, 283, 'product', 0, 1406, 'M', 0);
REPLACE INTO ?:images_links (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES(1170, 283, 'product', 0, 1407, 'A', 0);

REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1395, 't-1.jpg', 220, 220);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1396, 't-13.jpg', 2400, 2838);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1397, 't-6.jpg', 400, 543);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1398, 't-3.jpg', 400, 543);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1399, 't-10.jpg', 1000, 1182);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1400, 't-11.jpg', 700, 700);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1401, 't-4.jpg', 2300, 2415);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1402, 't-12.jpg', 1500, 1500);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1403, 't-8.jpg', 1500, 1500);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1404, 't-2.jpg', 2300, 2415);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1405, 't-7.jpg', 1500, 1500);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1406, 't-5.jpg', 1500, 1500);
REPLACE INTO ?:images (`image_id`, `image_path`, `image_x`, `image_y`) VALUES(1407, 't-9.jpg', 700, 700);